name: f41
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #state_management
  flutter_riverpod: ^2.1.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #UI
  multi_select_flutter: ^4.1.3
  select_searchable_list: ^0.1.5
  animated_snack_bar: ^0.3.1

  #animation
  lottie: ^2.3.0

  #cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0

  #context
  kartal: 

  #network
  dio: ^5.1.1
  retrofit: ^4.0.1

  #api
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

  #navigation
  auto_route: ^6.0.5

  #di
  get_it: ^7.6.0
  injectable: ^2.1.1

  #utils
  equatable: ^2.0.5
  freezed: ^2.3.4
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^6.0.3
  injectable_generator: ^2.1.5
  retrofit_generator: ^7.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/


