// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBWdI2ZT7yGu15y8y_We0VFHoXrUz8eMA',
    appId: '1:875664835580:web:ee871d4945314123f82879',
    messagingSenderId: '875664835580',
    projectId: 'f41-flutterfire',
    authDomain: 'f41-flutterfire.firebaseapp.com',
    storageBucket: 'f41-flutterfire.appspot.com',
    measurementId: 'G-SX2Y3RG0BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzrjMhgR7wChpgTsaDiBKqeDww7DaQDyA',
    appId: '1:875664835580:android:cdedf32b58e7e6aaf82879',
    messagingSenderId: '875664835580',
    projectId: 'f41-flutterfire',
    storageBucket: 'f41-flutterfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjvSeoEQzsc2SVF7A3UJFlvHl_ODtZUw',
    appId: '1:875664835580:ios:93984e1517cb4f85f82879',
    messagingSenderId: '875664835580',
    projectId: 'f41-flutterfire',
    storageBucket: 'f41-flutterfire.appspot.com',
    androidClientId: '875664835580-kg7r8t82b299t35jogb3v2sc6usfgmod.apps.googleusercontent.com',
    iosClientId: '875664835580-hcc6gkla1d8f5fcp0gbgb012aj7q50ff.apps.googleusercontent.com',
    iosBundleId: 'com.erhangocen.connectopia',
  );
}
